### torch backward gradient

Demo of how tensor record previous operations

In [5]:
import torch

x = torch.tensor([2.0], requires_grad=True)
y = x ** 2 + 3 * x 

when we talk about the computation graph (or "tree"), it’s not just about computing the value of y. It’s about recording how y was computed — a kind of lazy evaluation graph — so that PyTorch can later compute derivatives using the chain rule.

In [6]:
print(type(y))       # <class 'torch.Tensor'>
print(y.grad_fn)     # Shows the function used to compute y

y.backward()         # compute dy/dx
print(x.grad)        # Should be 2x + 3 = 7.0

<class 'torch.Tensor'>
tensor([7.])


multiple tensor example, with partial derivatives

In [7]:
x1 = torch.tensor([1.0], requires_grad=True)
x2 = torch.tensor([2.0], requires_grad=True)

y = x1**2 + 3 * x2  # y depends on both x1 and x2
y.backward()

print(x1.grad)  # dy/dx1 = 2 * x1 = 2.0
print(x2.grad)  # dy/dx2 = 3


tensor([2.])
tensor([3.])
